### ISSUE TITLE
[Suggestion] Add Raw Chevon to forge:raw_meat

### ISSUE THREAD

**Issue by CherryPuppet** [MehVahdJukaar/ohmygoat#15]
Having an extra source of meat is nice and all, but in a larger modpack where other meats can be used in all sorts of recipes, not being able to use chevon for other recipes makes it not as useful.

The only other use for chevon:
![2024-07-10_17 59 39](https://github.com/MehVahdJukaar/ohmygoat/assets/162679788/b8f06dfa-6d45-4acd-a278-65180a2f3d58)

**Comment by MehVahdJukaar** [comment]
it is tagged as forge/meant/raw which as far as i know is the correct one

**Comment by MehVahdJukaar** [comment]
added it anyways
